<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2005

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2005 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:n1="http://www.cultuurdatabank.com/XMLSchema/CdbXSD/3.1/FINAL" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.cultuurdatabank.com/XMLSchema/CdbXSD/3.2/FINAL" exclude-result-prefixes="n1 xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/n1:cdbxml">

		<cdbxml>
			<xsl:attribute name="xsi:schemaLocation">http://www.cultuurdatabank.com/XMLSchema/CdbXSD/3.2/FINAL C:/XML/XSD/CDB_XSD_3_2/CDB_XSD_3_2.xsd</xsl:attribute>
					

			<!-- use this later <xsl:attribute name="xsi:schemaLocation">http://www.cultuurdatabank.com/XMLSchema/CdbXSD/3.2/FINAL http://www.cultuurdatabank.com/XMLSchema/CdbXSD/3.2/FINALCdbXSD.xsd</xsl:attribute> -->
			<xsl:for-each select="n1:events">
				<xsl:for-each select="n1:event">
					<event>
						<xsl:apply-templates select="@*"/>
						<xsl:apply-templates select="node()"/>
					</event>
				</xsl:for-each>
			</xsl:for-each>
			
		</cdbxml>
		
	</xsl:template>
	<xsl:template match="node()">
		
			<xsl:copy>
				<xsl:apply-templates select="@* | node()"/>
			</xsl:copy>
		
	</xsl:template>
	<xsl:template match="@*">
			<xsl:copy>
				<xsl:apply-templates select="@* | node()"/>
			</xsl:copy>
		
	</xsl:template>
</xsl:stylesheet>
